name: vframe
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - intel-openmp=2019.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pip=19.1.1
  - python=3.7.3
  - python_abi=3.7
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.29.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - aioredis==1.2.0
    - alembic==1.2.1
    - amqp==2.5.0
    - annoy==1.16.0
    - async-timeout==3.0.1
    - billiard==3.6.0.0
    - celery==4.3.0
    - chardet==3.0.4
    - click==7.0
    - colorlog==4.0.2
    - cycler==0.10.0
    - dacite==1.0.2
    - decorator==4.4.0
    - dnspython==1.16.0
    - eventlet==0.25.0
    - flask==1.1.1
    - flask-classful==0.14.2
    - flask-socketio==4.2.1
    - flask-sqlalchemy==2.4.0
    - flask-wtf==0.14.2
    - greenlet==0.4.15
    - h5py==2.10.0
    - hiredis==1.0.0
    - idna==2.8
    - imagehash==4.0
    - imageio==2.5.0
    - imutils==0.5.2
    - infinity==1.4
    - intervals==0.8.1
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - kombu==4.6.3
    - mako==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - monotonic==1.5
    - mysql-connector==2.2.9
    - networkx==2.3
    - numpy==1.17.0
    - onnxruntime==1.6.0
    - opencv-python==4.4.0.42
    - pbr==5.4.3
    - pdfkit==0.6.1
    - pdoc==0.3.2
    - pillow==6.1.0
    - protobuf==3.14.0
    - pymediainfo==4.0
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - python-dotenv==0.10.3
    - python-editor==1.0.4
    - python-engineio==3.9.3
    - python-socketio==4.3.1
    - pytz==2019.2
    - pywavelets==1.0.3
    - pyyaml==5.1.2
    - redis==3.3.8
    - requests==2.22.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.0
    - simplejson==3.16.0
    - six==1.12.0
    - sqlalchemy==1.3.6
    - sqlalchemy-utc==0.10.0
    - sqlalchemy-utils==0.34.1
    - sqlparse==0.3.0
    - tempita==0.5.2
    - torch==1.7.1
    - torchvision==0.8.2
    - tqdm==4.32.2
    - typing-extensions==3.7.4.3
    - urllib3==1.25.3
    - validators==0.13.0
    - vine==1.3.0
    - websocket-client==0.56.0
    - werkzeug==0.15.5
    - wtforms==2.2.1
    - wtforms-alchemy==0.16.9
    - wtforms-components==0.10.4
    - xmltodict==0.12.0

